apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-chaos-monkey
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels: 
            app: pod-chaos-monkey
        spec:
          serviceAccountName: monkey
          automountServiceAccountToken: true
          containers:
          - name: pod-chaos
            image: juandspy/pod-chaos-monkey:latest
            # imagePullPolicy: Never  # Uncomment this for local development
            resources:
              limits:
                memory: "128Mi"
                cpu: "50m"
            args:
              - --namespace=workloads
          restartPolicy: OnFailure