apiVersion: v1
kind: ServiceAccount
metadata:
  name: monkey
automountServiceAccountToken: false
---

apiVersion: rbac.authorization.k8s.io/v1
# Anyone with this role is able to list and delete a pod
kind: ClusterRole
metadata:
  name: pod-killer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "pod-killer" group to kill any pod in the cluster
kind: ClusterRoleBinding
metadata:
  name: pod-killer-global
subjects:
- kind: ServiceAccount
  name: monkey
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-killer
  apiGroup: rbac.authorization.k8s.io